model:
  id: "vllm-llama-3_2-1B-instruct-amd"
  user_id: "user-id"
  app_id: "app-id"
  model_type_id: "text-to-text"

build_info:
  python_version: '3.12'

inference_compute_info:
  cpu_limit: '1'
  cpu_memory: 13Gi
  num_accelerators: 1
  accelerator_type: ["AMD-*"]
  accelerator_memory: 21Gi

checkpoints:
  type: "huggingface"
  repo_id: "unsloth/Llama-3.2-1B-Instruct"
  when: "runtime"
