model:
  id: "stable-diffusion-2-depth"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: "3.11"

compute:
  instance: t4
  cloud: aws

checkpoints:
  type: huggingface
  repo_id: "stabilityai/stable-diffusion-2-depth"
  when: runtime
