model:
  id: "Qwen2_5-VL-3B-Instruct"
  user_id: "mogith-p-n"
  app_id: "test-co"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: '3.11'

inference_compute_info:
  cpu_limit: '3'
  cpu_memory: 14Gi
  num_accelerators: 1
  accelerator_type:
  - NVIDIA-L40S
  - NVIDIA-A100
  - NVIDIA-H100
  accelerator_memory: 38Gi

checkpoints:
  type: huggingface
  repo_id: Qwen/Qwen2.5-VL-3B-Instruct
  hf_token: ""
  when: runtime
