# This is the sample config file for the openai GPT model.
model:
  id: "gpt-4_1-mini"
  user_id: "user-id"
  app_id: "app-id"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: 500Mi
  num_accelerators: 0
  accelerator_type: null
  accelerator_memory: null