model:
  id: detr-resnet-50
  model_type_id: visual-detector

build_info:
  python_version: "3.11"

compute:
  instance: t4
  cloud: aws

checkpoints:
  type: huggingface
  repo_id: facebook/detr-resnet-50
