model:
  id: "MODEL_ID"
  user_id: "USER_ID"
  app_id: "APP_ID"
  model_type_id: "any-to-any"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: 500Mi
  num_accelerators: 0