build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: 1000m
  cpu_memory: 1Gi
  num_accelerators: 0
model:
  app_id: mcp-math-app
  id: mcp-math-model
  model_type_id: text-to-text
  user_id: mcp-math-user
