model:
  id: "tpu-model"
  user_id: "j1t745f6ga6o"
  app_id: "application-1755148569"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "2"
  cpu_memory: "2Gi"
  accelerator_type: ["GOOGLE-TPU-v5e"]
  num_accelerators: 1
