model:
  id: slack-mcp-server
  model_type_id: mcp

build_info:
  python_version: "3.11"

compute:
  instance: t3a.2xlarge

secrets:
  - id: "slack_key"
    type: "env"
    env_var: "SLACK_BOT_TOKEN"
    description: "API key of Slack for messaging and channel management"
