
model:
  id: "model_id"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "text-classifier"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "2000m"
  cpu_requests: "1"
  cpu_memory: "4Gi"
  cpu_memory_requests: "2Gi"
  num_accelerators: 0

concepts:
  - id: 'safe'
    name: 'safe'
  - id: 'drug'
    name: 'drug'
  - id: 'explicit'
    name: 'explicit'
  - id: 'gore'
    name: 'gore'
  - id: 'suggestive'
    name: 'suggestive'
