model:
  id: "nanonets-ocr-s"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: "3.11"

compute:
  instance: a10g
  cloud: aws

checkpoints:
  type: "huggingface"
  repo_id: "nanonets/Nanonets-OCR-s"
