model:
  id: firecrawl-browser-tools-mcp-server
  model_type_id: mcp

build_info:
  python_version: "3.11"

compute:
  instance: t3a.2xlarge

secrets:
  - id: "firecrawl_api_key"
    type: "env"
    env_var: "FIRECRAWL_API_KEY"
    description: "API key of Firecrawl for scraping and browsing"
