build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: 1000m
  cpu_memory: 1Gi
  num_accelerators: 0
model:
  app_id: mcp
  id: firecrawl-browser-tools-mcp-server
  model_type_id: text-to-text
  user_id: user_id
secrets:
  - id: "firecrawl_api_key"
    type: "env"
    env_var: "FIRECRAWL_API_KEY"
    description: "API key of Firecrawl for scraping and browsing"