model:
  id: gpt-oss-20b

build_info:
  python_version: "3.12"

compute:
  instance: g6e.2xlarge  # L40S from AWS

checkpoints:
  type: "huggingface"
  repo_id: "openai/gpt-oss-20b"
  when: "runtime"
