model:
  id: "hf-llama_3_2_1b_instruct-1"
  user_id: "frontend-user"
  app_id: "New-Model-Tests"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "13Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-*"]
  accelerator_memory: "18Gi"

checkpoints:
  type: "huggingface"
  repo_id: "unsloth/Llama-3.2-1B-Instruct"
  hf_token: "hf_token"
  when: "runtime"
