model:
  id: llama-32-1b-instruct

build_info:
  python_version: '3.11'

compute:
  instance: t4
  cloud: aws

checkpoints:
  repo_id: unsloth/Llama-3.2-1B-Instruct
  type: huggingface
  when: runtime

