model:
  id: "jinaai-embeddings-v3"
  model_type_id: "text-embedder"

build_info:
  python_version: "3.12"

compute:
  instance: t4
  cloud: aws

checkpoints:
  type: "huggingface"
  repo_id: "jinaai/jina-embeddings-v3"
  when: runtime
