# This is the sample config file for the llama model.

model:
  id: "llama-3_1-8B-instruct"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "text-to-text"

build_info:
  python_version: '3.11'

inference_compute_info:
  cpu_limit: '3'
  cpu_memory: 14Gi
  num_accelerators: 1
  accelerator_type:
  - NVIDIA-L40S
  - NVIDIA-A100
  - NVIDIA-H100
  accelerator_memory: 38Gi

checkpoints:
  type: huggingface
  repo_id: meta-llama/Llama-3.1-8B-Instruct
  hf_token: "hf_token"
  when: runtime
