build_info:
  python_version: '3.11'
inference_compute_info:
  cpu_limit: '3'
  cpu_memory: 15Gi
  num_accelerators: 0
model:
  app_id: local-dev-runner-app
  id: local-ollama-model
  model_type_id: text-to-text
  user_id: clarifai-user-id
